# ══════════════════════════════════════════════════════
#  pg_hba.conf — Authentication rules
# ══════════════════════════════════════════════════════

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local socket (containers internal use)
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust

# Allow all app connections from Docker network (trust — demo only)
host    all             all             172.28.0.0/24           trust

# Allow connections from host machine
host    all             all             0.0.0.0/0               md5

# Replication — allow replicator user from anywhere in demo network
host    replication     replicator      172.28.0.0/24           trust
host    replication     replicator      0.0.0.0/0               md5
